export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SAVE_ADDRESS_TO_LOCAL_STORAGE = 'SAVE_ADDRESS_TO_LOCAL_STORAGE';

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
